# frozen_string_literal: true

source "https://rubygems.org"

gem "roda", "~> 3.98"
gem "puma", ">= 6.0"
gem "sequel", "~> 5.90"
gem "sqlite3", ">= 2.1"
gem "rodauth", "~> 2.37"
gem "bcrypt"
gem "jwt"
