name: ingressos

services:
  web:
    build:
      context: ../14-ingressos
      dockerfile: Dockerfile
    command: bash -c "bundle exec ruby bin/migrate && bundle exec ruby bin/seed && exec bundle exec puma -C config/puma.rb"
    ports:
      - "9292:9292"
    environment:
      RACK_ENV: development
      DATABASE_URL: postgres://ingressos:ingressos@postgres:5432/ingressos
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: dev_jwt_compose
      WEBHOOK_SECRET: dev_webhook_compose
      SIDEKIQ: "1"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ../14-ingressos
      dockerfile: Dockerfile
    command: bash -c "bundle exec ruby bin/migrate && exec bundle exec sidekiq -r ./jobs/sidekiq.rb"
    environment:
      RACK_ENV: development
      DATABASE_URL: postgres://ingressos:ingressos@postgres:5432/ingressos
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: dev_jwt_compose
      WEBHOOK_SECRET: dev_webhook_compose
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ingressos
      POSTGRES_PASSWORD: ingressos
      POSTGRES_DB: ingressos
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  pg-data:
